spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_mini
    username: root
    password: shuipin5qin570
server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名和下划线命名的自动转换